# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialboard', '0005_remove_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialboard.Post'),
        ),
    ]
