# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialboard', '0007_auto_20190801_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=24)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialboard.Post')),
            ],
        ),
    ]
